name: Manual Release Checker

on:
  workflow_dispatch:
    inputs:
      days:
        default: 1
        description: 'Enter an amount of days from now to search.'
        required: true
        type: string
      channel_id:
        description: 'Enter the channel ID you want to check for. (Optional)'
        required: false
        type: string

jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - name: Set channel ID
        id: set_channel_id
        run: |
          if [ -z "${{ inputs.channel_id }}" ]; then
            echo "CHANNEL_ID=${{ secrets.Channel_Id }}" >> $GITHUB_ENV
          else
            echo "CHANNEL_ID=${{ inputs.channel_id }}" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Running Manual Release Checker...
        run: |
          python manual.py
        env:
          days: ${{ inputs.days }}
          email_password: ${{ secrets.email_password }}
          email: ${{ secrets.email }}
          api_key: ${{ secrets.api_key }}
          channel_id: ${{ env.CHANNEL_ID }}
