name: Manual Release Checker

on:
  workflow_dispatch:
    inputs:
      days:
        default: 1
        description: 'Enter an amount of days from now to search.'
        required: true
        type: number
      channel_id:
        description: 'Enter the channel ID you want to check for. (Optional)'
        required: false
        type: string

jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - name: Set channel ID
        id: set_channel_id
        run: echo "::set-output name=default_channel_id::${{ secrets.channel_id }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run YarnHub Release Checker
        run: python manual.py
        env:
          days: ${{ inputs.days }}
          email_password: ${{ secrets.email_password }}
          email: ${{ secrets.email }}
          api_key: ${{ secrets.api_key }}
          channel_id: ${{ coalesce(inputs.channel_id, steps.set_channel_id.outputs.default_channel_id) }}


          
    
