name: Manual Release Checker

on:
  workflow_dispatch:
    inputs:
      days:
        default: 1
        description: 'Enter an amount of days from now to search.'
        required: true
        type: number
      channel_id:
        default: ${{ secrets.channel_id }}
        description: 'Enter the channel ID you want to check for. (Optional)'
        required: false
        type: string

jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run YarnHub Release Checker
        run: python manual.py
        env:
          days: ${{ inputs.days }}
          email_password: ${{ secrets.email_password }}
          email: ${{ secrets.email }}
          api_key: ${{ secrets.api_key }}
          channel_id: ${{ inputs.channel_id }}

          
    
