name: Manual YarnHub Release Checker

on:
  workflow_dispatch:
    inputs:
      days:
        default: 1
        description: 'Enter an amount of days from now to search!'
        required: true
        type: number

jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run YarnHub Release Checker
        run: python main.py
        env:
          days: ${{ inputs.days }}
    
